-- Event archival + transactional email support (event creation emails,
-- payment receipts, and the 30-days-after-expiry photo archive-and-purge
-- job). Run this in the Supabase SQL Editor after security-hardening.sql
-- and paystack-migration.sql have already been applied. See EMAIL_SETUP.md
-- for the Resend account setup and Edge Function deploys this depends on.

-- 1. Tracks whether an event's photos have already been archived and
--    purged, so the daily cron job below doesn't reprocess the same event
--    every day forever.
ALTER TABLE events ADD COLUMN IF NOT EXISTS photos_purged_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_events_expiry_unpurged
  ON events(expiry_date) WHERE photos_purged_at IS NULL;

-- 2. Private bucket for the per-event zip archives generated by the
--    purge-expired-events Edge Function. Deliberately NOT public — the
--    only access is a short-lived signed URL emailed to the organizer,
--    generated with the service role key, which bypasses storage RLS
--    entirely. No storage.objects policies are added for this bucket on
--    purpose: default-deny is correct here.
INSERT INTO storage.buckets (id, name, public)
VALUES ('event-archives', 'event-archives', false)
ON CONFLICT (id) DO NOTHING;

-- 3. Daily cron job that calls purge-expired-events. 30 days after an
--    event's expiry_date (itself already 30 days after the event's
--    end_date — see AdminEventManager.js), that Edge Function zips the
--    event's photos, emails the organizer a signed download link, and
--    deletes the photos to free up storage.
--
--    pg_net's http_post needs the Authorization header to actually reach
--    the function, but this .sql file is often committed to source
--    control — so the service role key and function URL are stored in
--    Supabase Vault (encrypted at rest) instead of being pasted here in
--    plaintext. Vault ships enabled by default on Supabase projects.
--
--    ONE-TIME SETUP — replace the placeholders and run these two selects
--    FIRST, before the cron.schedule call below (get the values from
--    Settings -> API):
--
--      select vault.create_secret('<your-service-role-key>', 'service_role_key');
--      select vault.create_secret('https://<your-project-ref>.supabase.co/functions/v1/purge-expired-events', 'purge_function_url');
--
--    If you ever rotate the service role key, update the secret instead of
--    re-creating it:
--      select vault.update_secret(id, '<new-service-role-key>')
--      from vault.secrets where name = 'service_role_key';

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

SELECT cron.schedule(
  'purge-expired-events-daily',
  '0 3 * * *', -- 03:00 UTC daily
  $$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'purge_function_url'),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key'),
      'Content-Type', 'application/json'
    ),
    body := '{}'::jsonb
  );
  $$
);

-- Verify it's scheduled:
--   select jobid, jobname, schedule, active from cron.job;
-- Check recent runs:
--   select * from cron.job_run_details order by start_time desc limit 10;
-- Remove the job entirely if you ever need to:
--   select cron.unschedule('purge-expired-events-daily');
